### ISSUE TITLE
is it working

### ISSUE THREAD

**Issue by stickylab** [devzhuchuanbo/Canoe-Warrior-Unity2021#1]
is this playable project ?

**Comment by devzhuchuanbo** [comment]
Yes, this is a playable proejct, feel free to copy, fork, edit.

**Comment by stickylab** [comment]
thanks for the reply

**Comment by stickylab** [comment]
![image](https://github.com/devzhuchuanbo/Canoe-Warrior-Unity2021/assets/87752832/098a04cc-1edc-4fc3-b287-ff46993f71c4)
looks like very old project

**Comment by stickylab** [comment]
![image](https://github.com/devzhuchuanbo/Canoe-Warrior-Unity2021/assets/87752832/d3969fe5-a116-4e5e-812d-9ed2d8df0891)

**Comment by stickylab** [comment]
![image](https://github.com/devzhuchuanbo/Canoe-Warrior-Unity2021/assets/87752832/e18b4f12-acf5-4d95-a6d8-0a118403555e)
 ti thought it about paddling canoe ,,,,,,,,
